autopilot_config: vmware-tanzu-samples
repositories:
- name: vmware-tanzu-samples
  resource_type: { name: git }
  source:
    uri: https://github.com/vmware-tanzu-labs/concourse-pipeline-samples.git
    branch: master

pipelines:
- name: scheduled-pipeline
  manifest: concourse-pipeline-patterns/time-triggered-pipelines/01-single-time-trigger/scheduled-pipeline-01.yml
  repository: vmware-tanzu-samples
