autopilot_config: concourse-examples
repositories:
- name: concourse-examples
  uri: https://github.com/concourse/examples.git
  branch: master

pipelines:
- name: concourse-pipeline-vars
  manifest: pipelines/pipeline-vars.yml
  repository: concourse-examples
  vars:
    hello: autopilot