---
jobs:
- name: hello-world
  plan:
  - task: greet-world
    vars:
      username: ((username))
    config:
      platform: linux
      image_resource:
        type: registry-image
        source: { repository: busybox }
      run:
        path: echo
        args: ["Hello ((username))!"]
