---
resources:
- name: autopilot-example
  type: git
  source:
    uri: https://github.com/efejjota/concourse-autopilot-example.git
    branch: main

jobs:
- name: hello-world
  plan:
  - get: autopilot-example
    trigger: true

  - task: greet-world
    file: autopilot-example/tasks/hello-world.yml
    vars:
      username: ((username))
